describe('webdriver.io page', () => {
    it('should have the right title', () => {
        browser.url('https://katalon-test.s3.amazonaws.com/aut/html/form.html')
        const begin = new Date()
        $('#first-name').setValue('First Name')
        $('#last-name').setValue('Last Name')
        $('input[type=radio][name=gender]').click()
        $('#dob').click()
        $('body > div.datepicker.datepicker-dropdown.dropdown-menu.datepicker-orient-left.datepicker-orient-top > div.datepicker-days > table > tbody > tr:nth-child(1) > td:nth-child(1)').click()
        $('#address').setValue('Address')
        $('#email').setValue('email@email.com')
        $('#password').setValue('Password')
        $('#company').setValue('Company')
        $('#role').selectByVisibleText('Manager')
        $('#expectation').selectByVisibleText('High salary')
        $('.development-ways .checkbox:nth-child(1) input').click()
        $('.development-ways .checkbox:nth-child(2) input').click()
        $('.development-ways .checkbox:nth-child(3) input').click()
        $('.development-ways .checkbox:nth-child(4) input').click()
        $('.development-ways .checkbox:nth-child(5) input').click()
        $('.development-ways .checkbox:nth-child(6) input').click()
        $('#comment').setValue('Comment')
        $('#submit').click()
        const end = new Date()
        console.log(end.getTime() - begin.getTime())
    })
})